kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "php-pipeline"
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "app", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/renatoppuccini/demo-php.git"
      ref: pipeline
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
